version: "3.8"

services:
    kitsune-bot:
        image: ghcr.io/topisenpai/kitsune-bot:latest
        container_name: kitsune-bot
        restart: unless-stopped
        env_file:
            - conf.env
        networks:
            - traefik
        expose:
            - 80
        labels:
            com.centurylinklabs.watchtower.enable: true
            traefik.enable: true
            traefik.http.routers.kitsune-bot.rule: Host(`kitsune-bot.topi.wtf`)
            traefik.http.routers.kitsune-bot.entrypoints: https
            traefik.http.services.kitsune-bot.loadbalancer.server.port: 80

networks:
    traefik:
        external: true
