version: "3.8"

services:
    reddit-bot:
        image: ghcr.io/topisenpai/anicord:latest
        container_name: anicord-bot
        restart: unless-stopped
        env_file:
            - conf.env
        networks:
            - database
            - traefik
        expose:
            - 80
        labels:
            traefik.enable: true
            traefik.http.routers.anicord-bot.rule: Host(`anicord.topi.wtf`)
            traefik.http.routers.anicord-bot.entrypoints: https
            traefik.http.services.anicord-bot.loadbalancer.server.port: 80

networks:
    database:
        external: true
    traefik:
        external: true
