version: "3.8"

services:
    godrive:
        image: ghcr.io/topi314/godrive:master
        container_name: godrive
        restart: unless-stopped
        volumes:
            - ./config.json:/var/lib/godrive/godrive.json
            - ./storage/:/storage/
        networks:
            - database
            - traefik
        expose:
            - 80
        ports:
            - 0.0.0.0:8888:80
        labels:
            com.centurylinklabs.watchtower.enable: true
            traefik.enable: true
            traefik.http.routers.godrive.rule: Host(`godrive.zip`)
            traefik.http.routers.godrive.entrypoints: https
            traefik.http.services.godrive.loadbalancer.server.port: 80
    img:
        image: ghcr.io/topi314/godrive:master
        container_name: img
        restart: unless-stopped
        volumes:
            - ./img-config.json:/var/lib/godrive/godrive.json
        networks:
            - database
            - traefik
        expose:
            - 80
        labels:
            com.centurylinklabs.watchtower.enable: true
            traefik.enable: true
            traefik.http.routers.img.rule: Host(`img.topi.wtf`)
            traefik.http.routers.img.entrypoints: https
            traefik.http.services.img.loadbalancer.server.port: 80

networks:
    database:
        external: true
    traefik:
        external: true
