version: '3.8'

services:
    # MongoDB database
    database:
        image: mongo
        restart: always
        networks:
            - revolt
        volumes:
            - ./.data/db:/data/db

    # REVOLT API server (Delta)
    api:
        image: revoltchat/server
        restart: always
        env_file: conf.env
        environment:
            - REVOLT_MONGO_URI=mongodb://database
        expose:
            - 8000
            - 9000
        networks:
            - revolt
            - traefik
        labels:
            traefik.enable: true
            traefik.http.routers.revolt-api.rule: Host(`api.revolt.$PRIMARY_DOMAIN`)
            traefik.http.routers.revolt-api.entrypoints: https
            traefik.http.services.revolt-api.loadbalancer.server.port: 8000

            traefik.http.routers.revolt-ws.rule: Host(`ws.revolt.$PRIMARY_DOMAIN`)
            traefik.http.routers.revolt-ws.entrypoints: https
            traefik.http.services.revolt-ws.loadbalancer.server.port: 9000

    # REVOLT Web App
    web:
        image: revoltchat/client:master
        restart: always
        env_file: conf.env
        expose:
            - 5000
        labels:
            traefik.enable: true
            traefik.http.routers.revolt-web.rule: Host(`revolt.$PRIMARY_DOMAIN`)
            traefik.http.routers.revolt-web.entrypoints: https
            traefik.http.services.revolt-web.loadbalancer.server.port: 5000

    # S3-compatible storage server
    minio:
        image: minio/minio
        restart: always
        command: server /data
        env_file: conf.env
        volumes:
            - ./.data/minio:/data
        networks:
            - revolt
        expose:
            - 9000

    # Create buckets for minio.
    createbuckets:
        image: minio/mc
        networks:
            - revolt
        env_file: conf.env
        entrypoint: >
            /bin/sh -c "
            while ! curl -s --output /dev/null --connect-timeout 1 http://minio:9000; do echo 'Waiting minio...' && sleep 0.1; done;
            /usr/bin/mc alias set minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
            /usr/bin/mc mb minio/attachments;
            /usr/bin/mc mb minio/avatars;
            /usr/bin/mc mb minio/backgrounds;
            /usr/bin/mc mb minio/icons;
            /usr/bin/mc mb minio/banners;
            exit 0;
            "

    # REVOLT file hosting service (Autumn)
    autumn:
        image: revoltchat/autumn
        restart: always
        env_file: conf.env
        environment:
            - AUTUMN_MONGO_URI=mongodb://database
        networks:
            - revolt
        expose:
            - 3000
        labels:
            traefik.enable: true
            traefik.http.routers.revolt-autumn.rule: Host(`autumn.revolt.$PRIMARY_DOMAIN`)
            traefik.http.routers.revolt-autumn.entrypoints: https
            traefik.http.services.revolt-autumn.loadbalancer.server.port: 3000

    # REVOLT metadata and image proxy (January)
    january:
        image: revoltchat/january
        restart: always
        networks:
            - revolt
        ports:
            - 3000
        labels:
            traefik.enable: true
            traefik.http.routers.revolt-january.rule: Host(`january.revolt.$PRIMARY_DOMAIN`)
            traefik.http.routers.revolt-january.entrypoints: https
            traefik.http.services.revolt-january.loadbalancer.server.port: 3000

networks:
    revolt:
        name: revolt
    traefik:
        external: true
