#!/bin/bash

docker-compose -f nginx/docker-compose.yml down

docker-compose -f teamcity/docker-compose.yml down

docker-compose -f kittybot/docker-compose.yml down

docker-compose -f kittybot-dev/docker-compose.yml down

docker-compose -f item-warehouse/docker-compose.yml down

docker-compose -f minecraft/docker-compose.yml down

docker-compose -f database/docker-compose.yml down

docker-compose -f portainer/docker-compose.yml down
