#!/bin/bash

docker-compose -f nginx/docker-compose.yml down

docker-compose -f kittybot-website/docker-compose.yml down

docker-compose -f kittybot/docker-compose.yml down

docker-compose -f teamcity/docker-compose.yml down

docker-compose -f database/docker-compose.yml down
