version: "3.8"

services:
    wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard
        restart: unless-stopped
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
            - LOG_CONFS=true
        volumes:
            - ./wg0.conf:/config/wg0.conf
            - /lib/modules:/lib/modules
        networks:
            - wireguard

    haproxy:
        image: haproxy:alpine
        container_name: haproxy
        restart: unless-stopped
        network_mode: service:wireguard
        depends_on:
            - wireguard
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
    wireguard:
        name: wireguard
