version: "3.8"

services:
    wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
            - LOG_CONFS=true
        volumes:
            - ./wg0.conf:/config/wg0.conf
            - /lib/modules:/lib/modules
