version: "3.8"

services:
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        restart: unless-stopped
        ports:
            - 0.0.0.0:53:53
        expose:
            - 80
        env_file:
            - conf.env
        networks:
            - traefik
        volumes:
            - ./data/pihole/:/etc/pihole/
            - ./data/etc-dnsmasq.d/:/etc/dnsmasq.d/
        cap_add:
            - NET_ADMIN
        labels:
            traefik.enable: true
            traefik.http.routers.pihole.rule: Host(`pihole.topi.wtf`)
            traefik.http.routers.pihole.entrypoints: https
            traefik.http.routers.pihole.middlewares: authelia@docker
            traefik.http.services.pihole.loadbalancer.server.port: 80

networks:
    traefik:
        external: true
