#
# A Sample Teleport configuration file.
#
# Things to update:
#  1. license.pem: You only need a license from https://dashboard.goteleport.com
#     if you are an Enterprise customer.
#===
version: v2
teleport:
    nodename: teleport
    data_dir: /var/lib/teleport
    log:
        output: stderr
        severity: INFO
        format:
            output: text
    ca_pin: ""
    diag_addr: ""
auth_service:
    enabled: "yes"
    listen_addr: 0.0.0.0:3025
    public_addr: teleport.topi.wtf:443
    cluster_name: topi.wtf
    proxy_listener_mode: multiplex
    client_idle_timeout: never
    disconnect_expired_cert: no
    web_idle_timeout: 20m
    client_idle_timeout_message: "bye bye"
ssh_service:
    enabled: "yes"
    listen_addr: 0.0.0.0:3022
    public_addr: teleport.topi.wtf:3022
    commands:
        - name: hostname
          command: [hostname]
          period: 1m0s
        - name: teleport-version
          command: ["/bin/sh", "-c", "/usr/local/bin/teleport version --raw"]
          period: 1m0s
proxy_service:
    enabled: "yes"
    web_listen_addr: 0.0.0.0:3080
    public_addr: teleport.topi.wtf:443
    ssh_public_addr: teleport.topi.wtf:443
    tunnel_public_addr: teleport.topi.wtf:443
    https_keypairs:
        - key_file: /letsencrypt/key.pem
          cert_file: /letsencrypt/cert.pem
