#
# A Sample Teleport configuration file.
#
# Things to update:
#  1. license.pem: You only need a license from https://dashboard.goteleport.com
#     if you are an Enterprise customer.
#===
version: v2
teleport:
    nodename: teleport
    data_dir: /var/lib/teleport
    log:
        output: stderr
        severity: INFO
        format:
            output: text
    ca_pin: ""
    diag_addr: ""
auth_service:
    enabled: "yes"
    listen_addr: 0.0.0.0:3025
    public_addr: teleport.topi.wtf
    cluster_name: topi.wtf
    proxy_listener_mode: separate
    client_idle_timeout: never
    disconnect_expired_cert: no
    web_idle_timeout: 20m
    client_idle_timeout_message: "ah fuck"
ssh_service:
    enabled: "yes"
    listen_addr: 0.0.0.0:3022
    public_addr: teleport.topi.wtf
    commands:
        - name: hostname
          command: [hostname]
          period: 1m0s
proxy_service:
    enabled: "yes"
    listen_addr: 0.0.0.0:3023
    public_addr: teleport.topi.wtf

