global:
    checkNewVersion: true
    sendAnonymousUsage: false

log:
    level: INFO

accessLog: {}

metrics:
    prometheus:
        buckets:
            - 0.1
            - 0.3
            - 1.2
            - 5.0
        addEntryPointsLabels: true
        addServicesLabels: true

entryPoints:
    http:
        address: ':80'
        proxyProtocol:
            insecure: true # not directly exposed
        http:
            redirections:
                entryPoint:
                    to: https
                    permanent: true
    https:
        address: ':443'
        proxyProtocol:
            insecure: true # not directly exposed
        http:
            tls:
                certResolver: cloudflare
                domains:
                    - main: topi.wtf
                      sans:
                          - '*.topi.wtf'
                    - main: 'kittybot.de'
                      sans:
                          - '*.kittybot.de'
                    - main: 'hastebin.de'
                      sans:
                          - '*.hastebin.de'
                    - main: 'xgob.in'
                      sans:
                          - '*.xgob.in'

providers:
    docker:
        exposedByDefault: false
        swarmMode: false
        network: traefik
    file:
        directory: '/configs'
        watch: true

api:
    dashboard: true
    insecure: true

certificatesResolvers:
    cloudflare:
        acme:
            # testing server
            # caserver: https://acme-staging-v02.api.letsencrypt.org/directory
            email: mail@topi.wtf
            storage: /letsencrypt/acme.json
            dnsChallenge: 
                provider: cloudflare
                delayBeforeCheck: 120
                resolvers:
                    - opal.ns.cloudflare.com
                    - trace.ns.cloudflare.com
