metrics:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  configs:
    - name: agent
      scrape_configs:
        - job_name: agent
          static_configs:
            - targets: ['localhost:9090']
              labels:
                  service: agent

        - job_name: prometheus
          static_configs:
            - targets: ['prometheus:9090']
              labels:
                  service: prometheus

        - job_name: host
          static_configs:
            - targets: ['node-exporter:9100']
              labels:
                  service: node-exporter

        - job_name: traefik
          static_configs:
            - targets: ['traefik:8080']
              labels:
                  service: traefik

        - job_name: promtail
          static_configs:
            - targets: ['promtail:9080']
              labels:
                  service: promtail

        - job_name: cadvisor
          static_configs:
            - targets: ['cadvisor:8080']
              labels:
                  service: cadvisor

        - job_name: kittybot
          static_configs:
            - targets: ['kittybot:8080']
              labels:
                  service: kittybot

        - job_name: lavalink
          static_configs:
            - targets: ['lavalink:2333', 'lavalink2:2333']
              labels:
                  service: lavalink

        - job_name: gobin
          static_configs:
            - targets: ['gobin:9100']
              labels:
                  service: gobin
      remote_write:
        - url: http://cortex:9090/api/prom/push

logs:
  configs:
    - name: agent
      positions:
        filename: /tmp/positions.yaml
      clients:
        - url: http://loki:3100/loki/api/v1/push
      scrape_configs:
        - job_name: system
          static_configs:
            - targets: [localhost]
              labels:
                job: varlogs
                __path__: /var/log/*log

        - job_name: docker
          static_configs:
            - targets:  [localhost]
              labels:
                job: docker
                __path__: /var/lib/docker/containers/*/*log

          pipeline_stages:
            - json:
                expressions:
                    output: log
                    stream: stream
                    attrs:
            - json:
                expressions:
                    tag:
                source: attrs
            - regex:
                expression: (?P<container_name>(?:[^|]*[^|]))
                source: tag
            - timestamp:
                format: RFC3339Nano
                source: time
            - labels:
                stream:
                container_name:
            - output:
                source: output

traces:
  configs:
    - name: agent
      receivers:
        otlp:
          protocols:
            http:
      remote_write:
        - endpoint: loki:3200
          insecure: true
      batch:
        timeout: 5s
        send_batch_size: 100
integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true

