server:
    http_listen_address: 0.0.0.0
    http_listen_port: 9080

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://loki:3100/loki/api/v1/push

scrape_configs:
    - job_name: system
      static_configs:
          - targets:
                - localhost
            labels:
                job: varlogs
                __path__: /var/log/*log

    - job_name: docker
      static_configs:
          - targets:
                - localhost
            labels:
                job: docker
                __path__: /var/lib/docker/containers/*/*log
                machine: pve

      pipeline_stages:
          - json:
                expressions:
                    output: log
                    stream: stream
                    attrs:
          - json:
                expressions:
                    tag:
                source: attrs
          - regex:
                expression: (?P<container_name>(?:[^|]*[^|]))
                source: tag
          - timestamp:
                format: RFC3339Nano
                source: time
          - labels:
                # tag:
                stream:
                container_name:
          - output:
                source: output
