version: '3.8'

services:
  server:
    image: ghcr.io/matrix-org/synapse
    container_name: synapse
    restart: unless-stopped
    environment:
      UID: 1000
      GID: 1000
    healthcheck:
      disable: true
    ports:
      - 127.0.0.1:8008:8008
    networks:
      - traefik
    volumes:
      - ./data/:/data
    labels:
      traefik.enable: true
      traefik.http.routers.matrix-server.rule: Host(`chat.topi.wtf`) && ( PathPrefix(`/_matrix/`) || PathPrefix(`/_synapse/client/`) )
      traefik.http.routers.matrix-server.entrypoints: https
      traefik.http.services.matrix-server.loadbalancer.server.port: 8008
  web:
    image: ghcr.io/cinnyapp/cinny:latest
    container_name: cinny
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./cinny.json/:/usr/share/nginx/html/config.json
    labels:
      traefik.enable: true
      traefik.http.routers.matrix-web.rule: Host(`chat.topi.wtf`)
      traefik.http.routers.matrix-web.entrypoints: https
      traefik.http.services.matrix-web.loadbalancer.server.port: 80
  static:
    image: nginx:alpine
    container_name: matrix-well-known
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static/:/data/:ro
    labels:
      traefik.enable: true
      traefik.http.routers.matrix-static.rule: Host(`topi.wtf`) && ( PathPrefix(`/.well-known/`) )
      traefik.http.routers.matrix-static.entrypoints: https
      traefik.http.services.matrix-static.loadbalancer.server.port: 8080

networks:
  traefik:
    external: true
