version: "3.8"

services:
    mailserver:
        image: docker.io/mailserver/docker-mailserver:latest
        container_name: mailserver
        restart: unless-stopped
        stop_grace_period: 1m
        cap_add:
            - NET_ADMIN
        hostname: mail
        domainname: topi.wtf
        env_file:
            - conf.env
        volumes:
            - ./data/mail-data/:/var/mail/
            - ./data/mail-state/:/var/mail-state/
            - ./data/mail-logs/:/var/log/mail/
            - ./data/config/:/tmp/docker-mailserver/
            - /etc/localtime:/etc/localtime:ro
            - ../traefik/data/letsencrypt/acme.json:/etc/letsencrypt/acme.json:ro
        networks:
            wireguard:
                ipv4_address: 192.168.180.6
        ports:
            - 0.0.0.0:25:25    # SMTP  (explicit TLS => STARTTLS)
            - 0.0.0.0:143:143  # IMAP4 (explicit TLS => STARTTLS)
            - 0.0.0.0:465:465  # ESMTP (implicit TLS)
            - 0.0.0.0:587:587  # ESMTP (explicit TLS => STARTTLS)
            - 0.0.0.0:993:993  # IMAP4 (implicit TLS)
        healthcheck:
            test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
            timeout: 3s
            retries: 0

networks:
    wireguard:
        external: true
