version: "3.8"

services:
    reposilite:
        image: dzikoysk/reposilite:latest
        container_name: reposilite
        restart: unless-stopped
        environment:
#            - REPOSILITE_OPTS=--token admin:secret
             - JAVA_OPTS=-Dreposilite.s3.pathStyleAccessEnabled=true
        volumes:
            - ./data/:/app/data/
        networks:
            - traefik
            - minio
        expose:
            - 8080
        labels:
            traefik.enable: true
            traefik.http.routers.reposilite.rule: Host(`maven.topi.wtf`)
            traefik.http.routers.reposilite.entrypoints: https
            traefik.http.services.reposilite.loadbalancer.server.port: 8080

networks:
    traefik:
        external: true
    minio:
        external: true
