version: "3.8"

services:
    wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard-server
        restart: unless-stopped
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
            - SERVERURL=wireguard.topi.wtf
            - SERVERPORT=51820
            - PEERS=nas
            - PEERDNS=auto
            - LOG_CONFS=true
        volumes:
            - ./data:/config
            - /lib/modules:/lib/modules
            - ./up.sh:/up.sh
        ports:
            - 0.0.0.0:51820:51820/udp # wireguard
            - 0.0.0.0:80:80           # traefik http
            - 0.0.0.0:443:443         # traefik https
            - 0.0.0.0:3025:3025       # teleport
            - 0.0.0.0:25565:25565     # minecraft
            - 0.0.0.0:25:25           # SMTP  (explicit TLS => STARTTLS)
            - 0.0.0.0:143:143         # IMAP4 (explicit TLS => STARTTLS)
            - 0.0.0.0:465:465         # ESMTP (implicit TLS)
            - 0.0.0.0:587:587         # ESMTP (explicit TLS => STARTTLS)
            - 0.0.0.0:993:993         # IMAP4 (implicit TLS)
            - 0.0.0.0:5432:5432       # database-dev
