version: "3.8"

services:
    wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard-server
        restart: unless-stopped
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
            - SERVERURL=wireguard.topi.wtf
            - SERVERPORT=51820
            - PEERS=nas
            - PEERDNS=auto
            - LOG_CONFS=true
        volumes:
            - ./data:/config
            - /lib/modules:/lib/modules
            - ./up.sh:/up.sh
        ports:
            - 0.0.0.0:51820:51820/udp
            - 0.0.0.0:80:80
            - 0.0.0.0:443:443
            - 0.0.0.0:25565:25565
            - 0.0.0.0:3025:3025
