http:
    middlewares:
        global-headers:
            headers:
                customResponseHeaders:
                    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
                    X-Content-Type-Options: nosniff
