http:
  routers:
    mo:
      rule: Host(`turtle.topi.wtf`)
      entrypoints: 
        - https
      service: turtle
      #middlewares:
      #  - authelia@docker
  services:
    turtle:
      loadbalancer:
        servers:
          # - url: http://192.168.178.44:80
          # - url: http://192.168.178.44:8081
          - url: http://192.168.178.44/picture/1/frame/
