version: "3.8"

services:
    topi-website:
        image: ghcr.io/topi314/topi.wtf:master
        container_name: topi.wtf
        restart: unless-stopped
        networks:
            - traefik
        expose:
            - 8080
        volumes:
            - ./config.yml:/etc/topi.wtf/config.yml
        labels:
            com.centurylinklabs.watchtower.enable: true
            traefik.enable: true
            traefik.http.routers.topi-website.rule: Host(`topi.wtf`) || Host(`www.topi.wtf`)
            traefik.http.routers.topi-website.entrypoints: https
            traefik.http.routers.topi-website.middlewares: www-topi-website-redirect
            traefik.http.services.topi-website.loadbalancer.server.port: 8080
            traefik.http.middlewares.www-topi-website-redirect.redirectregex.regex: https://topi.wtf/(.*)
            traefik.http.middlewares.www-topi-website-redirect.redirectregex.replacement: https://www.topi.wtf/$${1}

networks:
    traefik:
        external: true
