version: "3.8"

services:
    wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard
        restart: unless-stopped
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
            - SERVERURL=wg.topi.wtf
            - SERVERPORT=51820
            - PEERDNS=auto
            - LOG_CONFS=true
        volumes:
            - ./data/wireguard:/config
            - /lib/modules:/lib/modules
        networks:
            - traefik
        ports:
            - 51820:51820/udp # wireguard
            - 80:80           # http
            - 443:443         # traefik https
            - 3023:3023       # teleport ssh
            - 3024:3024       # teleport auth
            - 3025:3025       # teleport auth tls
            - 25565:25565     # minecraft
            - 5432:5432       # database-dev
            - 22:22           # gitea ssh
            - 222:222         # server ssh
    haproxy:
        image: haproxy
        container_name: haproxy
        restart: unless-stopped
        network_mode: service:wireguard
        depends_on:
            - wireguard
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    wg-ui:
        image: ngoduykhanh/wireguard-ui:latest
        container_name: wg-ui
        user: "1000:1000"
        cap_add:
            - NET_ADMIN
        networks:
            - traefik
        environment:
            - SESSION_SECRET
            - WGUI_USERNAME=topi
            - WGUI_PASSWORD=topi
        volumes:
            - ./data/ui:/app/db
            - ./data/wireguard:/etc/wireguard
        labels:
            traefik.enable: true
            traefik.http.routers.wg-ui.rule: Host(`wg.topi.wtf`)
            traefik.http.routers.wg-ui.entrypoints: https
            traefik.http.services.wg-ui.loadbalancer.server.port: 80
networks:
    traefik:
        external: true
