version: '3.7'

services:
    disgo-butler:
        image: docker.pkg.github.com/disgoorg/disgo-butler:latest
        container_name: disgo-butler
        restart: unless-stopped
        command: --sync-commands=false --sync-db=false
        volumes:
            - ./config.json:/config.json:rw
        networks:
            - disgo-butler
            - database
            - traefik
        labels:
            traefik.enable: true
            traefik.http.routers.disgo-butler.rule: Host(`butler.$PRIMARY_DOMAIN`)
            traefik.http.routers.disgo-butler.entrypoints: https
            traefik.http.services.disgo-butler.loadbalancer.server.port: 80

networks:
    disgo-butler:
        name: disgo-butler
    database:
        external: true
    traefik:
        external: true
