version: "3.8"

services:
    img:
        image: ghcr.io/topisenpai/godrive:master
        container_name: img
        restart: unless-stopped
        volumes:
            - ./config.json:/var/lib/godrive/godrive.json
        networks:
            - database
            - traefik
        expose:
            - 80
        labels:
            com.centurylinklabs.watchtower.enable: true
            traefik.enable: true
            traefik.http.routers.img.rule: Host(`img.topi.wtf`)
            traefik.http.routers.img.entrypoints: https
            traefik.http.services.img.loadbalancer.server.port: 80

networks:
    database:
        external: true
    traefik:
        external: true
